export const pets = [
    {
      id: 1,
      name: "Tuffy",
      category: "Dog",
      breed: "German Shepherd",
      // precautions: "these are the precatuions",
      // interests: "these are the interests of the dog",
      from: "15/01/2023",
      to: "15/01/2023",
    },
    {
      id: 2,
      name: "Snowball",
      category: "Cat",
      breed: "Fluffy",
      from: "31/01/2023",
      to: "01/01/2023",
    },
    {
      id: 1,
      name: "Tuffy",
      category: "Dog",
      breed: "German Shepherd",
      from: "15/01/2023",
      to: "15/01/2023",
    },
    {
      id: 2,
      name: "Snowball",
      category: "Cat",
      breed: "Fluffy",
      from: "31/01/2023",
      to: "01/01/2023",
    },
    {
      id: 2,
      name: "Snowball",
      category: "Cat",
      breed: "Fluffy",
      from: "31/01/2023",
      to: "01/01/2023",
    },
    {
      id: 1,
      name: "Tuffy",
      category: "Dog",
      breed: "German Shepherd",
      from: "15/01/2023",
      to: "15/01/2023",
    },
    {
      id: 2,
      name: "Snowball",
      category: "Cat",
      breed: "Fluffy",
      from: "31/01/2023",
      to: "01/01/2023",
    },
    {
      id: 2,
      name: "Snowball",
      category: "Cat",
      breed: "Fluffy",
      from: "31/01/2023",
      to: "01/01/2023",
    },
    {
      id: 1,
      name: "Tuffy",
      category: "Dog",
      breed: "German Shepherd",
      from: "15/01/2023",
      to: "15/01/2023",
    },
    {
      id: 2,
      name: "Snowball",
      category: "Cat",
      breed: "Fluffy",
      from: "31/01/2023",
      to: "01/01/2023",
    },
  ];


export const userPets = [
  {
    id: 1,
    name: "Tuffy",
    age: 8,
    type: "Dog",
    breed: "Labrador",
    precautions: "these are the precatuions",
    interests: "these are the interests of the dog",
  },
  {
    id: 2,
    name: "meow",
    age: 5,
    type: "cat",
    breed: "Unknown",
    precautions: "these are the precatuions for cat",
    interests: "these are the interests of the cat",
  },
  {
    id: 1,
    name: "Tuffy",
    age: 8,
    type: "Dog",
    breed: "Labrador",
    precautions: "these are the precatuions",
    interests: "these are the interests of the dog",
  },
  {
    id: 2,
    name: "meow",
    age: 5,
    type: "cat",
    breed: "Unknown",
    precautions: "these are the precatuions for cat",
    interests: "these are the interests of the cat",
  },
  {
    id: 1,
    name: "Tuffy",
    age: 8,
    type: "Dog",
    breed: "Labrador",
    precautions: "these are the precatuions",
    interests: "these are the interests of the dog",
  },
  {
    id: 2,
    name: "meow",
    age: 5,
    type: "cat",
    breed: "Unknown",
    precautions: "these are the precatuions for cat",
    interests: "these are the interests of the cat",
  },
];